# from cloneWith
# https://github.com/CloneWith/osu/blob/b46c9fd4185263be2fbe39eef4a0616ac620430d/.github/workflows/build-release.yml
name: Build Release
run-name: Build Release (${{inputs.profile}}-${{inputs.version}})

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build Profile'
        type: choice
        required: true
        default: 'Release'
        options:
          - Debug
          - Release
      version:
        description: 'Version Number'
        required: true
        default: '0.0.0'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./osu

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os.fullname}}
    strategy:
      matrix:
        os:
          - { prettyname: Windows, fullname: windows-latest }
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: osu

      - name: Checkout framework
        uses: actions/checkout@v4
        with:
          repository: shanden-tournament/osu-framework
          path: osu-framework
          ref: shanden-custom
      
      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Compile
        run: dotnet publish -f net8.0-windows -r win-x64 -c ${{inputs.profile}} -o ${{ github.workspace }}/osu/Release /p:Version=${{ inputs.version }} ${{ github.workspace }}/osu/osu.Desktop/osu.Desktop.csproj

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: osu-build-${{inputs.profile}}-${{inputs.version}}@${{matrix.os.fullname}}
          path: ${{ github.workspace }}/osu/Release/**
